name: Lint

on:
  pull_request:

jobs:
  prettier:
    permissions:
      contents: write
    name: Prettier (write)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          only_changed: True
          commit_message: "(lint): Run prettier against ${{ github.sha }}"
          prettier_options: "--write ."
